### ISSUE TITLE
Project Roadmap?

### ISSUE THREAD

**Issue by kingdomcoding** [elixir-desktop/desktop#16]
Hey. Thank you for your effort on this project.

I'm very interested in what elixir-desktop turns out to be eventually.

Do you think spelling out a roadmap for the future of the project will be helpful?

I believe it could increase interest and also encourage participation and discussions.

**Comment by dominicletz** [comment]
Good idea! Just added a short section. Let me know what other info I should add https://hexdocs.pm/desktop/readme.html#status-roadmap
