### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by daya** [elixir-desktop/desktop#21]
Hi has anyone successfully created an iOS app using Elixir Desktop? if yes, then

- What was your experience like?
- What are some getting started pointers that you can share?
- What are some pitfalls to avoid?

**Comment by dominicletz** [comment]
Yes, you can get our app from the AppStore https://apps.apple.com/us/app/diode-drive/id1605222443 it's all Elixir.

- Experience: Cross-compiling Erlang was a pain, but you only need to do it once. And the sample iOS app ships with a precompiled version.
- Getting started: Get the sample iOS app https://github.com/elixir-desktop/ios-example-app, install XCode, brew and elixir and launch it, modify it... We're doing most development just in Desktop mode and then validate the app in the simulator.
- Pitfalls: 
  - The Erlang version in the app and erlang version you compile your mix project with must be the same. The iOS sample app  still has a pretty custom Erlang version as it was the first to work on iOS. So easiest is to install the special iOS version on your machine and use that for compilation. 
    ```
    mkdir -p ~/projects/
    kerl build git https://github.com/diodechain/otp.git diode/beta 24.beta
    kerl install 24.beta ~/projects/24.beta
    ```
  - Touch events are different from click events. If you build your live-view / javascript frontend code you have to deal with touch events differently than pure click events on desktop.
  - When submitting to the AppStore debug symbols don't work -- I haven't found out how to make them work, but it always complains about the Erlang binaries not having the right debug symbols.
