### ISSUE TITLE
Using database with it?

### ISSUE THREAD

**Issue by x-ji** [elixir-desktop/desktop#22]
(Searched the issues and the ElixirForum thread but didn't seem to find a similar discussion.)

I once tried to distribute an Elixir app to non-programmer end users on all platforms. The server version of the app uses Postgres, which I tried to replace with SQLite in the local version. There were several annoyances: 1. SQLite support in Ecto 3 was bad (not sure if it's now improved) 2. some related libraries failed to compile on Windows AFAIK (Needed some VC++ support.)

Does this project (intend to) support using DB on the host together with the app? If so, what would be the best approach to do it? 🙂

**Comment by dominicletz** [comment]
Did you have a look at the sample app https://github.com/elixir-desktop/desktop-example-app ?

It's using the new ecto_sqlite3 library which has good ecto support. Give it a try.

**Comment by x-ji** [comment]
That's really cool! I saw that exqlite is also included in the runtimes for iOS and Android, so one can also use the full SQLite functionalities with iOS and Android builds right?

**Comment by x-ji** [comment]
And by the way, if I want to expose the app via a port to a frontend on the desktop builds, this should be trivially achievable right? (The use case I mentioned was to run a separate frontend app also locally and have it connect to an API backend.) I can't imagine why it shouldn't, but would just like to make sure :)

**Comment by dominicletz** [comment]
> And by the way, if I want to expose the app via a port to a frontend on the desktop builds, this should be trivially achievable right? (The use case I mentioned was to run a separate frontend app also locally and have it connect to an API backend.) I can't imagine why it shouldn't, but would just like to make sure, since the example case mentioned in the READMEs use LiveView :)

Sure this works as well. You just have to signal the port somehow. In the Android and iOS builds the frontend is defacto another app and it's using environment variables to pass the port addresses.
