### ISSUE TITLE
Support registering custom urls `todoapp://...` and open them in app

### ISSUE THREAD

**Issue by dominicletz** [elixir-desktop/desktop#3]
Similar to how zoom invites ask users whether the meeting should be opened with the zoom app, we want elixir-desktop apps to be enabled to be the handlers for custom URI protocols. 

The current insight into this is that to support this we have to:

- On MacOS: Add an entry to the apps .plist that specifies the URL protocol
- On Linux: Add an entry to the apps .dekstop file that specifies the URL protocol
- On Windows: Add a registry entry

Additional there needs to be a callback handler able to react to this once the app receives an URI.

**Comment by wojtekmach** [comment]
@dominicletz any ideas how to capture this event on macOS? In swift something like this seems to do the trick:

```swift
class AppDelegate: NSObject, NSApplicationDelegate {
    func applicationDidFinishLaunching(_ aNotification: Notification) {
        NSAppleEventManager
            .shared()
            .setEventHandler(
                self,
                andSelector: #selector(handleURL(event:reply:)),
                forEventClass: AEEventClass(kInternetEventClass),
                andEventID: AEEventID(kAEGetURL)
            )

        // ...
    }

    @objc func handleURL(event: NSAppleEventDescriptor, reply: NSAppleEventDescriptor) {
        // ...
    }
```

but I couldn't find whether wx has some support for it. If it doesn't, I guess we'd need to manually bridge ourselves with native code?

**Comment by dominicletz** [comment]
@wojtekmach since OTP 24.1 you can subscribe to those events using `:wx.subscribe()`

https://github.com/erlang/otp/commit/3e398c1d6b2be8b684cb3e3224cea1821bf49b7f

It will send `{:open_url, Url}` to the subscriber. E.g. desktop/env.ex is doing that but at the moment but ignoring all such events / only handles `:reopen`

**Comment by dominicletz** [comment]
This can be done now, but needs `:wx.subscribe_events()` and then handling `{:open_url, url}` and `{:open_file, file}`
