### ISSUE TITLE
 Is there a way to have 2 icons when using elixir-desktop? 

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [elixir-desktop/desktop#33]
Background
---------

I have a personal project that is an elixir desktop application for PC Windows. It works pretty well, but now I want to give it an icon. 

This is usually done in the following module:

```
defmodule WebInterface.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  alias Desktop
  alias Manager
  alias WebInterface.{Endpoint, Telemetry}
  alias WebInterface.Live.MenuBar

  @impl true
  def start(_type, _args) do
    children = [
      Telemetry,
      {Phoenix.PubSub, name: WebInterface.PubSub},
      Endpoint,
      Manager,
      {Desktop.Window,
       [
         app: :web_interface,
         id: WebInterface,
         title: "Market Manager",
         size: {900, 960},
         menubar: MenuBar,
         icon: "static/images/resized_logo_4.png", # THIS IS WHERE THE ICON IS SET
         url: &WebInterface.Endpoint.url/0
       ]}
    ]

    opts = [strategy: :one_for_one, name: WebInterface.Supervisor]
    Supervisor.start_link(children, opts)
  end

  @impl true
  def config_change(changed, _new, removed) do
    WebInterface.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

Problem
-----

The issue here is that I have to use the same image for both the Windows taskbar and the top icon of the app:

![b3f4b901220c425f4ac2763e53488228340d125d](https://user-images.githubusercontent.com/2980392/200361427-013385c8-1ea5-46ab-b1dd-163d20f4b904.jpeg)

The issue here is that while the logo on the bottom Windows bar (marked yellow) is nice, the one in the top is distorted and pretty horrible.

The fix to this would be to have an icon for the bottom and one for the top. 
However after checking the [demo app](https://github.com/elixir-desktop/desktop-example-app) I didn't find a way of doing this.

Question
------

Is this possible to achieve?  If so, how?

**Comment by dominicletz** [comment]
From here: https://elixirforum.com/t/is-there-a-way-to-have-2-icons-when-using-elixir-desktop/51621/2?u=dominicletz

There are two ways to do this:

1) You call `Desktop.Menu.set_icon` after application startup to change the taskbar icon like the sample application does: [desktop-example-app/menu.ex at 1661b9bf28c09bbbd2ce87ffe5e4dd1dd8e21ccf · elixir-desktop/desktop-example-app · GitHub 1](https://github.com/elixir-desktop/desktop-example-app/blob/1661b9bf28c09bbbd2ce87ffe5e4dd1dd8e21ccf/lib/todo_app/menu.ex#L35)
1) You use the new `:taskbar_icon` option in v1.4.2 :

```elixir
{Desktop.Window,
       [
         app: :web_interface,
         id: WebInterface,
         title: "Market Manager",
         size: {900, 960},
         menubar: MenuBar,
         icon: "static/images/resized_logo_4.png",
         taskbar_icon: "static/images/taskbar_logo.png",
         url: &WebInterface.Endpoint.url/0
```

Hope this helps!
