### ISSUE TITLE
Desktop App does not close and always reopens

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [elixir-desktop/desktop#41]
Background
----------

I have a basic Desktop app with the following config:

`application.ex`
```
defmodule WebInterface.Application do
  use Application

  alias Desktop
  alias Manager
  alias WebInterface.{Endpoint, PubSub, Telemetry}

  @impl true
  def start(_type, _args) do
    children = [
      Telemetry,
      {Phoenix.PubSub, name: PubSub},
      Endpoint,
      Manager,
      {Desktop.Window,
       [
         app: :web_interface,
         id: WebInterface,
         title: "Market Manager",
         size: {900, 900},
         icon: "static/images/resized_logo_5_32x32.png",
         url: &WebInterface.Endpoint.url/0
       ]}
    ]

    opts = [strategy: :one_for_one, name: WebInterface.Supervisor]
    Supervisor.start_link(children, opts)
  end

  @impl true
  def config_change(changed, _new, removed) do
    WebInterface.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

This is basically the default configuration. You will notice the desktop app does not have a `MenuBar`. This is on purpose, as I don't want one. 

Problem
-------

The issue here is that no matter what, the application won't close:

![Animation](https://github.com/elixir-desktop/desktop/assets/2980392/b501972d-a6f3-4833-8d8f-98a0914f8036)

It always reopens. 
After checking the code of Desktop, I believe the issue could be in ` Desktop.Window`:

```
def init(options) do
    window_title = options[:title] || Atom.to_string(options[:id])
    size = options[:size] || {600, 500}
    min_size = options[:min_size]
    app = options[:app]
    icon = options[:icon]
    taskbar_icon = options[:taskbar_icon]
    # not supported on mobile atm
    menubar = unless OS.mobile?(), do: options[:menubar]
```

Namely, I am lead to believe there is a difference for Mobile apps and normal apps. 

Funnily enough, if add a `MenuBar`, then the application does _eventually_ close, even though it takes forever for the process behind it to terminate:

```
{Desktop.Window,
       [
         app: :web_interface,
         id: WebInterface,
         title: "Market Manager",
         size: WindowUtils.calculate_window_size(0.4, 0.7),
         menubar: MenuBar,
         icon: "static/images/resized_logo_5_32x32.png",
         url: &WebInterface.Endpoint.url/0
       ]}
```

Cliking on the Menubar `Quit` option also closes the application. 

Questions
----------

Am I forced to have a Menubar, if my I have a Desktop app?
How can this be fixed?

**Comment by Fl4m3Ph03n1x** [comment]
After some more digging with the help of the forum community, we were able to pinpoint some differences between using the `Menu -> Quit` option and closing the window via the `X` button. 

Summarizing the words of better people (https://elixirforum.com/t/desktop-app-does-not-close-and-always-reopens/56585/2?u=fl4m3ph03n1x):

> the “Quit” menu item ends up calling [Window.quit/0 2](https://github.com/elixir-desktop/desktop/blob/bab89d1701064ced6fd54de4630cc741f53ab9a2/lib/desktop/window.ex#L450-L457), which ultimately kill -9s the BEAM from outside (!!).

I have some questions about this code:

```
  def shutdown() do
    spawn(&halt/0)
  end

  @spec halt() :: no_return()
  defp halt() do
    Process.sleep(300)

    # With System.stop(0) shutdown of the WebView takes
    # a very long time (10+ seconds), and wxWidgets cleanup
    # often crashes on macOS
    # System.stop(0)

    kill_heart()
    System.halt(0)
  end
```

- Why do we need to spawn a process ? The process will kill everything anyway, why not have the father do it?
- If System.stop crashes on MacOS (and only on macOS), can't we make a check for the OS and use `System.stop` to cleanly shutdown Windows, Linux and Android?


> the “close window” icon ends up calling [Window.close_window/2 2](https://github.com/elixir-desktop/desktop/blob/bab89d1701064ced6fd54de4630cc741f53ab9a2/lib/desktop/window.ex#L547-L570) which returns {:stop, :normal, ui} - which will result in the parent Supervisor restarting the Window process.

This is consistent with my findings:

```
  def close_window(wx(userData: pid), inev) do
    IO.puts("USER PRESSED  'X'")
    # if we don't veto vetoable events on MacOS the app freezes.
    if :wxCloseEvent.canVeto(inev) do
      :wxCloseEvent.veto(inev)
    end

    GenServer.cast(pid, :close_window)
    :ok
  end

  @doc false
  def handle_cast(:close_window, ui = %Window{frame: frame, taskbar: taskbar}) do
    IO.puts("RECEIVER CLOSE_WINDOW EVENT")

    if not :wxFrame.isShown(frame) do
      IO.puts("SHUTTING DOWN OS")
      OS.shutdown()
    end

    IO.puts("OS SHUTDOWN AVOIDED")
    IO.inspect(taskbar, label: "TASKBAR")
    if taskbar == nil do
      :wxFrame.hide(frame)
      {:stop, :normal, ui}
    else
      :wxFrame.hide(frame)
      {:noreply, ui}
    end
  end
```

Will result in the log:

```
iex(5)> USER PRESSED  'X'
iex(5)> RECEIVER CLOSE_WINDOW EVENT
iex(5)> OS SHUTDOWN AVOIDED
iex(5)> TASKBAR: nil
```
Furthermore, I can confirm that setting the restart strategy to `:transient` solves the issue:

```
%{
        id: Desktop.Window,
        start: {Desktop.Window, :start_link, [[
          app: :web_interface,
          id: WebInterface,
          title: "Market Manager",
          size: WindowUtils.calculate_window_size(0.4, 0.8),
          menubar: MenuBar,
          icon: "static/images/resized_logo_5_32x32.png",
          url: fn -> "#{WebInterface.Endpoint.url()}/#{@landing_page}" end
        ]]},
        restart: :transient,
        shutdown: 5_000
      }
```

However, this raises some questions for me:

-  Why are we skipping the `OS.shutdown()` call? Should the `if` expression not be reversed?
- If the code is correct as is, is setting the restart strategy to transient the only solution? (If yes, we should probably make this more user friendly).

**Comment by dominicletz** [comment]
> def shutdown() do
>     spawn(&halt/0)
>   end
> 
>   @spec halt() :: no_return()
>   defp halt() do
>     Process.sleep(300)
> 
>     # With System.stop(0) shutdown of the WebView takes
>     # a very long time (10+ seconds), and wxWidgets cleanup
>     # often crashes on macOS
>     # System.stop(0)
> 
>     kill_heart()
>     System.halt(0)
>   end

Yeah as mentioned both - Windows and MacOS have problems here. On Windows for some reason the shutdown can take anywhere from 10 - 60 seconds. Which is really unfortunately especially if what we want to achieve is a quick App restart. That was ultimately the reason to introduce this hard kill here.

Both issues 1) the MacOS crash 2) the Window slow shutdown, seem to be underlying issues in wxWidgets and with a newer version these might go away -- This code is built based on experience with wxWidgets 3.1.6

**Comment by dominicletz** [comment]
> However, this raises some questions for me:
> 
>     * Why are we skipping the `OS.shutdown()` call? Shouldn't the `if not :wxFrame.isShown(frame) do` expression be reversed?

This is working around a macOS peculiarity and I missed documenting that in the code. On macOS there is no way to differentiate between the window close event here or the application close event (when you want to shutdown your mac for example) -- So this code assumes that if there is a "close_window" event coming in while the window is not actually show then => it must be actually an application close event (because the mac shuts down, or the os is asking the app to quit). Again on windows this code *should* not have any relevance - if it does that was not intended.
 

> 
>     * If the code is correct as is, is setting the restart strategy to transient the only solution? (If yes, we should probably make this more user friendly).
> 
> 
> In addition to all of this, using the `Menu -> Quit` option will kill everything, including the terminal session, why pressing the `X` button will leave the terminal session open, even though the window is closed.

My primary use case involves always a taskbar icon and a single long lived window. When writing the `taskbar == nil` branch I thought there could be many different strategies for windows management. Such as keeping multiple windows around. But now I think you're right and we could simplify this to just call `OS.shutdown()` in the `taskbar == nil` branch as well. If users really want to create multi-window apps that could be it's own flag in the future. 
```
if taskbar == nil do
   OS.shutdown()
else
```

**Comment by Fl4m3Ph03n1x** [comment]
> Both issues 1) the MacOS crash 2) the Window slow shutdown, seem to be underlying issues in wxWidgets and with a newer version these might go away -- This code is built based on experience with wxWidgets 3.1.6

Would it be feasable to update to [wxWidgets 3.2.2.1 Released](https://www.wxwidgets.org/news/2023/02/wxwidgets-3.2.2.1-released/) ?

**Comment by dominicletz** [comment]
I'm definitely curious about experience with that newer version. Would really like to offer prebuilt binaries with newer wxWidgets to make shipping easier.

**Comment by dpurrington** [comment]
I really want to use this library, but not being able to shutdown the app is kind of a deal-breaker. Is there no workaround?

**Comment by Fl4m3Ph03n1x** [comment]
@dpurrington the workaround is explained in the ticket I created.
If you do manage to use the latest version of wxWidgets, let us know how it goes. And also, please detail how you did it, as I am fairly curious.

**Comment by dpurrington** [comment]
Hey, I think I just figured this out. You don't put the window under a supervisor. Just call start_link. When you close the window, the whole process is taken down.
