### ISSUE TITLE
Packaging - any guides?

### ISSUE THREAD

**Issue by mxgrn** [elixir-desktop/desktop#47]
Thanks for the awesome project!

I looked around and can't seem to find anything regarding packaging for MacOS. Would you be able to provide any pointers?

**Comment by dominicletz** [comment]
This is still a work in progress integrating the `desktop_deployment` project and the `desktop-example-app`. You can see some of that here: https://github.com/elixir-desktop/desktop-example-app/tree/letz/ci

The goal is to bring this to a state where github CI builds the Windows/MacOS/Linux installers automatically for forked repos. A recent stumbling block on MacOS open source deployments was that they required the use of `DYLD_PRELOAD_PATHS` for locating the erlang libraries, but that is only available after signing the binaries.

That said I think I've found a way to make this work without `DYLD_PRELOAD_PATHS` in recent changes to the `desktop_deployment` repo and will update the macos ci build this or next week. 

Hopefully then the working code is the best reference -- But I agree some written down guide on the process would be sweet too.

**Comment by mxgrn** [comment]
Thanks! In mean while - and as a side note - I (re)discovered Tauri, along with some [community work](https://twitter.com/filipecabaco/status/1692135553511084123) to make it get along with Phoenix. Some initial results look very promising.
