### ISSUE TITLE
Menu / MenuBar not being displayed properly

### ISSUE THREAD

**Issue by FabioFusimoto** [elixir-desktop/desktop#8]
Hi! I've been trying to make a Desktop app built upon LiveView's basic template (the one generated with `mix phx.new <app> --live`) and basically following the same structure of the example app - [My Sample Project](https://github.com/FabioFusimoto/elixir-desktop-sample)

The [Supervisor start call](https://github.com/FabioFusimoto/elixir-desktop-sample/blob/master/lib/whatever/application.ex#L19) succeeds and both the [Menu](https://github.com/FabioFusimoto/elixir-desktop-sample/blob/master/lib/whatever/menu.ex) and [MenuBar](https://github.com/FabioFusimoto/elixir-desktop-sample/blob/master/lib/whatever/menubar.ex) `mount` calls print what they're supposed to. The problem is that the MenuBar does not appear and whenever I try to click the tray icon (which should display the "Close" option, but doesn't), the whole server crashes, with no error message whatsoever. Other features seem to work just fine: the separate window shows up properly and sending notifications is doable.

The provided sample app works flawlessly, which leads me to believe there's some extra configuration to do which I was not able to spot and mimic on my project. I'm running it on Windows 10, with Elixir 1.12.3 and Erlang/OTP 24

**Comment by kpanic** [comment]
I have a similar problem.
No menus at all in my test app.
I copied https://github.com/elixir-desktop/desktop-example-app/blob/main/lib/todo_app/menu.ex and the `.eex`
Copied https://github.com/elixir-desktop/desktop-example-app/blob/main/lib/todo_app/menubar.ex and the corresponding `.eex`
Renamed appropriately the module names for my app, however I did not see any visible menu.

Thanks a lot for this effort, it's fun! 💯

**Comment by dominicletz** [comment]
Thanks for reporting, this is a regression in 1.3.x, when the mount() was not making any assigns - I've just pushed the fix into 1.3.3 -- please upgrade (or make non-empty assigns in mount() )

Thanks for reporting!
FYI @mpotra

**Comment by kpanic** [comment]
Works perfectly for me! ❤️ Thanks!
